# yaml-language-server: $schema=../otherland.packet.schema.yaml

packets:
  CPkt:
    id: 0 # No real id. CPkt is only ever used as base for other packets
    subId: 0
    fields:
      - name: field8_0x8
        type: u64